name: Print fortran info
description: Simple showcasing variables

runs:
  steps:
  - name: Printing information
    shell: bash
    run: |
      echo $(which gfortran)
      echo $(which ifort)
      echo $(which ifx)
      echo $(which lfortran)
      echo $(which nvfortran)
      exit 0
