name: Print fortran info
description: Simple showcasing variables

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      echo $(which gfortran)
      exit 0
  - shell: bash
    run: |
      echo $(which ifort)
      exit 0
  - shell: bash
    run: |
      echo $(which ifx)
      exit 0
  - shell: bash
    run: |
      echo $(which lfortran)
      exit 0
  - shell: bash
    run: |
      echo $(which nvfortran)
      exit 0
