name: Print fortran info
description: Simple showcasing variables

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set +e
      echo gfortran=$(which gfortran)
      echo ifort=$(which ifort)
      echo ifx=$(which ifx)
      echo lfortran=$(which lfortran)
      echo nvfortran=$(which nvfortran)
      exit 0

  - shell: bash
    run: |
      echo FC=$FC
      echo FFLAGS=$FFLAGS

  - shell: bash
    run: |
      echo "Other found gfortran in same binary dir:"
      find $(dirname $FC) -name "gfortran*"
      echo "Other found flang in same binary dir:"
      find $(dirname $FC) -name "flang*"
