name: Print fortran info
description: Simple showcasing variables

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set +e
      names=(
        gfortran
        ifort
        ifx
        lfortran
        nvfortran
        f95
      )
      for v in ${names[@]} ; do
        exe=$(which $v)
        printf '\n\n%-10s : %s\n' $v $exe
        if [ -e "$exe" ]; then
          echo "  --version: $($exe --version)"
        fi
      done

  - shell: bash
    run: |
      echo FC=$FC
      echo FFLAGS=$FFLAGS

  - shell: bash
    run: |
      # unset options -e
      set +e
      DIR=$(dirname $(which $FC))
      echo "Other found gfortran in same binary dir:"
      find $DIR -name "gfortran*"
      echo "Other found flang in same binary dir:"
      find $DIR -name "flang*"
