name: Build and test fortran/pure

runs:
  using: "composite"
  steps:

  - uses: ./.github/reuse_steps/print_compiler

  - name: Intrinsic build
    shell: bash
    run: |
      cd fortran/pure
      obj=obj_host

      # Just to be sure it is the same as prior steps
      echo FC=$FC
      if [ -z "$FC" ]; then
        echo "Ensuring FC=gfortran..."
        export FC=gfortran
      fi
      opts=(
        --log-level=debug
        --log-context
        -DCMAKE_RULE_MESSAGES:BOOL=OFF
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      )
      cmake ${opts[@]} -S. -B$obj
      cmake --build $obj

      # And test
      cd $obj
      ./pure.x

  # Inspired by:
  # https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/arm-gcc-toolchain.cmake
  - name: Crosscompile for arm64
    shell: bash
    run: |
      cd fortran/pure
      obj=obj_arm64

      opts=(
        --log-level=debug
        --log-context
        -DCMAKE_RULE_MESSAGES:BOOL=OFF
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      )

      # Apparently forcing the generic
      [ $(uname -m) == "aarch64*" ] && exit 0
      [ $(uname -m) == "arm*" ] && exit 0
      if [[ $(uname) == "Darwin" ]]; then
        system_name=Darwin
        processor=ARM
        opts=(${opts[@]}
          -DCMAKE_OSX_ARCHITECHTURES=arm64
        )
      elif [[ $(uname) == "Linux" ]]; then
        system_name=Linux
        processor=ARM
      else
        system_name=Windows
        processor=ARM
      fi
      system_name=Generic

      opts=(${opts[@]}

        -DCMAKE_SYSTEM_NAME=$system_name
        -DCMAKE_SYSTEM_PROCESSOR=$processor
      )
      cmake ${opts[@]} -S. -B$obj
      cmake --build $obj

      # We can't test, check it fails when running
      cd $obj
      ./pure.x && exit 1 || exit 0
