name: Build and test fortran/pure

runs:
  using: "composite"
  steps:

  - uses: ./.github/reuse_steps/print_compiler

  - name: Intrinsic build
    shell: bash
    run: |
      # Just to be sure it is the same as prior steps
      echo FC=$FC
      cd fortran/pure
      opts=(
        --log-level=debug
        --log-context
        -DCMAKE_RULE_MESSAGES:BOOL=OFF
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      )
      cmake ${opts[@]} -S. -Bobj
      cmake --build obj

      # And test
      cd obj
      ./pure.x

  - name: Crosscompile for arm64
    shell: bash
    run: |
      [ $(uname -m) == "aarch64*" ] && exit 0
      [ $(uname -m) == "arm*" ] && exit 0
      if [[ $(uname) == "Darwin" ]]; then
        processor=arm64
      elif [[ $(uname) == "Linux" ]]; then
        processor=aarch64
      else
        processor=arm64
      fi
      opts=(
        --log-level=debug
        --log-context
        -DCMAKE_RULE_MESSAGES:BOOL=OFF
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

        -DCMAKE_CROSSCOMPILING=1
        -DCMAKE_SYSTEM_NAME=Generic
        -DCMAKE_SYSTEM_PROCESSOR=$processor
      )
      cmake ${opts[@]} -S. -Bobj
      cmake --build obj

      # We can't test
