name: C compiler info

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      # unset options -e
      set +e
      names=(
        gcc
        clang
        icc
        icx
        nvc
        cc
      )
      for v in ${names[@]} ; do
        exe=$(which $v)
        printf '\n\n%-10s : %s\n' $v $exe
        if [ -e "$exe" ]; then
          echo "  --version: $($exe --version)"
        fi
      done

  - shell: bash
    run: |
      echo CC=$CC
      echo CFLAGS=$CFLAGS

  - shell: bash
    run: |
      # unset options -e
      set +e
      # CC defined? Quick escape if that is the case...
      [ -z "$CC" ] && exit 0
      DIR=$(dirname $(which $CC))
      echo "Other found gcc in same binary dir:"
      find $DIR -name "*gcc*"
      echo "Other found clang in same binary dir:"
      find $DIR -name "*clang*"
