name: "c/pure"

on:
  push:
    branches: [ "main" ]

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      os: ${{ steps.os.outputs.os }}

    steps:
      - name: Define OS
        id: os
        run: |
          echo 'os=["ubuntu-latest", "macos-12", "macos-latest", "windows-latest"]' >> "$GITHUB_OUTPUT"

  intrinsic_c_linux:
    name: intrinsic
    needs: define-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/c_pure

  conda_default_c_linux:
    name: conda default
    runs-on: ${{ matrix.os }}
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda

      - name: install gcc
        shell: bash
        run: |
          conda install gcc

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/c_pure
