name: "fortran/pure"

on:
  push:
    branches: [ "main" ]

jobs:
  setup_fortran:
    name: setup_fortran
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2023.2'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: '23.11'}

    steps:

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Printing information
        shell: bash
        run: |
          echo $(which gfortran)
          echo $(which ifort)
          echo $(which ifx)
          echo $(which lfortran)
          echo $(which nvfortran)
          exit 0

      - name: Build
        id: build
        run: |
          cd fortran/pure
          cmake --log-level=debug --log-context -Bobj -S.
          cmake --log-level=debug --log-context --build obj

      - name: Test
        run: |
          cd obj
          ./pure.x
