name: "fortran/pure"

on:
  push:
    branches: [ "main" ]

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      os: ${{ steps.os.outputs.os }}

    steps:
      - name: Define OS
        id: os
        run: |
          echo 'os=["ubuntu-latest", "macos-12", "macos-latest", "windows-latest"]' >> "$GITHUB_OUTPUT"

  intrinsic_fortran_linux:
    name: intrinsic
    needs: define-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}
        exclude:
          # Neither of these has gfortran by default
          - os: macos-12
          - os: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/fortran_pure

  setup_fortran:
    name: setup_fortran
    needs: define-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}
        toolchain:
          - {compiler: gcc, version: 11}

    steps:

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/fortran_pure

      - if: matrix.os == 'macos*'
        uses: ./.github/reuse_steps/fortran_pure
        with:
          osx_sdk: 12.0

      - if: matrix.os == 'macos*'
        uses: ./.github/reuse_steps/fortran_pure
        with:
          osx_sdk: 13.0

  conda_default_fortran_linux:
    name: conda default
    runs-on: ${{ matrix.os }}
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,defaults

      - name: install fortran-compiler
        shell: bash -el {0}
        run: |
          conda info
          conda list

          # unset options -e
          set +e

          names=(
            gfortran
            flang
          )

          for package in ${names[@]} ; do
            conda search $package
            if [ $? -eq 0 ]; then
              conda install $package
              break
            fi
          done

          conda info
          conda list

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/fortran_pure
