name: "fortran/pure"

on:
  push:
    branches: [ "main" ]

jobs:
  intrinsic_fortran_linux:
    name: intrinsic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, macos-latest, windows-latest]
        exclude:
          # Neither of these has gfortran by default
          - os: macos-12
          - os: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/fortran_pure

  setup_fortran:
    name: setup_fortran
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 11}

    steps:

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/reuse_steps/print_host
      - uses: ./.github/reuse_steps/fortran_pure
